default_map: basement-full
maps:
  - basement-full
  - ward_24
wormholes:
  elevator_1:
    connected_locations:
      basement-full:
        position: [0.0 ,0.0]
        orientation: 0.0
        floor: -1
      ward_24:
        position: [0.0 ,0.0]
        orientation: 0.0
        floor: 4
  elevator_2:
    connected_locations:
      basement-full:
        position: [0.0 ,0.0]
        orientation: 0.0
        floor: -1
      ward_24:
        position: [0.0 ,0.0]
        orientation: 0.0
        floor: 4
  elevator_3:
    connected_locations:
      basement-full:
        position: [0.0 ,0.0]
        orientation: 0.0
        floor: -1
      ward_24:
        position: [0.0 ,0.0]
        orientation: 0.0
        floor: 4
